name: ${project.name}
main: space.devport.wertik.spleefflagexpansion.SpleefFlagPlugin
version: ${project.version}
authors: [Wertik1206 (qwz)]
depend: [WorldGuard]
commands:
  spleefflagexpansion:
    aliases: [sfe, sf, spleefflag]
    description: Main plugin command