name: ${project.name}
main: space.devport.wertik.blockregenflag.BlockRegenFlagPlugin
version: ${project.version}
authors: [Wertik1206 (qwz)]
depend: [WorldGuard]
commands:
  blockregenflag:
    aliases: [brflag, brf]
    description: Main plugin command